//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class basic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public basic()
        {
            this.educations = new HashSet<education>();
            this.skills = new HashSet<skill>();
            this.works = new HashSet<work>();
            this.leaves = new HashSet<leave>();
            this.raises = new HashSet<raise>();
            this.reimburses = new HashSet<reimburse>();
        }
        [Required(ErrorMessage = "Please enter Employee ID")]
        [Display(Name = "Employee ID : ")]
        public int empid { get; set; }
        [Required(ErrorMessage = "Please enter Name")]
        [Display(Name = "Employee Name : ")]
        [StringLength(20)]
        public string empname { get; set; }
        [Required(ErrorMessage = "Please select Employee Type")]
        [Display(Name = "Employee Type : ")]
        public string emptype { get; set; }
        [Required(ErrorMessage = "Please enter Department ID")]
        //[Range(101, 104, ErrorMessage = "Department ID  Must be between 101 to 104")]
        [Display(Name = "Department ID: ")]
        public Nullable<int> deptid { get; set; }
        [Required(ErrorMessage = "Please enter Date of Birth")]
        [Display(Name = "Date of Birth : ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> dob { get; set; }

        [Required(ErrorMessage = "Please enter email ")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email :")]
        [MaxLength(50)]
        public string email { get; set; }
        [Display(Name = "Mobile Number: ")]
        [Required(ErrorMessage = "Mobile Number is required.")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Mobile Number.")]
        public string mobile { get; set; }
        [Display(Name = "Address: ")]
        [Required(ErrorMessage = "Address is required.")]
        public string address { get; set; }
        [Required(ErrorMessage = "Please enter Date of Birth")]
        [Display(Name = "Date of Joining : ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> dateofjoin { get; set; }
        [Required(ErrorMessage = "Please select Gender")]
        [Display(Name = "Gender : ")]
        public string gender { get; set; }
        [DisplayName("Employee Photo : ")]
        public string emp_photo_path { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
       
    
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<education> educations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skill> skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work> works { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leave> leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<raise> raises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reimburse> reimburses { get; set; }
    }
}
