//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class raise
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Employee id is required")]
        [Display(Name = "Employee ID:")]
        public Nullable<int> empid { get; set; }
        [Required(ErrorMessage = "Enter your current location")]
        [Display(Name = "Current Location:")]
        public string curloc { get; set; }
        [Required(ErrorMessage = "Provide your preferred contact timing")]
        [Display(Name = "Preferred Contact Timing :")]
        public string precontim { get; set; }
        [Required(ErrorMessage = "Give short description")]
        [Display(Name = "Short Description :")]
        public string shortdes { get; set; }
        [Required(ErrorMessage = "This field is Required")]
        [Display(Name = "Description :")]
        public string des { get; set; }
    
        public virtual basic basic { get; set; }
    }
}
