//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class reimburse
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Please enter Employee ID")]
        [Display(Name = "Employee ID : ")]
        public Nullable<int> empid { get; set; }
        [Required]
        [Display(Name = "Type of Claim: ")]
        public string ct { get; set; }
        [Required]
        [Display(Name = "Bill No:")]
        public Nullable<int> bno { get; set; }
        [Required]
        [Display(Name = "Date:")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> bd { get; set; }
        [Required]
        [Display(Name = "Bill amount:")]
        public Nullable<int> bamnt { get; set; }
        [Required]
        [Display(Name = "Gst amount:")]
        public Nullable<int> gstamnt { get; set; }
        [Required]
        [Display(Name = "Base amount:")]
        public Nullable<int> baamnt { get; set; }
        [Display(Name = "Remarks:")]
        public string remarks { get; set; }
        [Required]
        [Display(Name = "Seller Gst number:")]
        public Nullable<int> segstin { get; set; }
    
        public virtual basic basic { get; set; }
    }
}
