//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class skill
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Please enter Employee ID")]
        [Display(Name = "Employee ID : ")]
        public Nullable<int> empid { get; set; }
        [Required]
        [Display(Name = "Primary Skills :")]
        public string primary_skills { get; set; }
        [Display(Name = "Other Skills: ")]
        public string other_skills { get; set; }
    
        public virtual basic basic { get; set; }
    }
}
