//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class work
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Please enter Employee ID")]
        [Display(Name = "Employee ID : ")]
        public Nullable<int> empid { get; set; }
        [Required]
        [Display(Name = "Previously worked company Name:")]
        public string previous_emp_comp_name { get; set; }
        [Display(Name = "Years of Experience:")]
        public string year_exp { get; set; }
        [Required]
        [Display(Name = "Work domain:")]
        public string work_domain { get; set; }
    
        public virtual basic basic { get; set; }
    }
}
